site_name: DeveloperPy
site_url: http://developerpy.com.br
site_author: Miguel Tenório

theme:
  name: material
  
  language: pt-BR

  favicon: assets/favicon.png
  logo: assets/img/logo.png

  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest
    - navigation.footer
  
  plugins:
    - search:
      lang: pt-BR
    - offline
  
  nav:
  - Home: index.md

  - Trilha Ciência de dados:
    - 1.-Trilha-Ciência-de-dados/index.md
    - Níveis:
      - Nível 1: 1.1-Níveis/nv1.md
      - Nível 2: 1.1-Níveis/nv2.md
      - Nível 3: 1.1-Níveis/nv3.md
    - Assuntos:
      - 1.2-Assuntos/index.md
  - Trilha de estudos Inteligência Artificial:
    - Trilha-Inteligência-Artificial/index.md
    - Níveis:
      - Nível 1:
      - Nível 2:
      - Nível 3:
    - Assuntos:
  - Sobre mim:
    - Sobre/index.md

  icon:
    repo: fontawesome/brands/github

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: black
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

repo_url: https://github.com/MiguelHCJS/Data-Science
repo_name: MiguelHCJS/Data-Science
 
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MiguelHCJS

  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
      - manage

copyright: Copyright &copy; 2023 Miguel Tenório
